version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./php.ini:/usr/local/etc/php/php.ini
        ports:
            - "9000:9000"
        networks:
            - laravel

    # web:
    #     image: nginx:alpine
    #     container_name: laravel-web
    #     restart: unless-stopped
    #     ports:
    #         - "80:80"
    #     volumes:
    #         - .:/var/www
    #         - ./nginx.conf:/etc/nginx/nginx.conf
    #     depends_on:
    #         - app
    #     networks:
    #         - laravel

    laravel-db:
        platform: linux/x86_64 # optional
        image: mysql:5.7
        container_name: laravel-db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
        driver: local
